import { Disposable } from "coc.nvim";
export declare class ListPicker implements Disposable {
    private state;
    private name;
    private source;
    private args;
    private items;
    private visibleItems;
    private readonly fuzzyMatch;
    private selected;
    private input;
    private generation;
    private previewGeneration;
    private previewTokenSource;
    private tokenSource;
    private task;
    private pollTimer;
    private renderTimer;
    private filterTimer;
    private limit;
    private visibleLimit;
    private previewEnabled;
    private previewMinColumns;
    show(name: string, args?: string[]): Promise<void>;
    resume(): Promise<void>;
    private open;
    close(): Promise<void>;
    dispose(): void;
    move(delta: number): Promise<void>;
    accept(): Promise<void>;
    showActions(): Promise<void>;
    private focusPrompt;
    private executeAction;
    private reload;
    private push;
    private scheduleFilter;
    private applyFilter;
    private cancelProducer;
    private pollInput;
    private scheduleRender;
    private render;
    private revealResultsLine;
    private updatePreview;
    private hidePreview;
    private applyLayout;
    private configurePreviewBuffer;
    private writePreviewBuffer;
    private detectFiletype;
    private focusPreviewLine;
    private context;
    private openWindows;
    private configureHighlights;
    private installCommands;
}
export declare function registerPickerCommands(picker: ListPicker): Disposable[];
